### PR TITLE
Normalize practice exercise names

### PR DESCRIPTION
**Pull request by kytrinyx**
We have added explicit exercise titles to the metadata.toml
files in problem-specifications.

This updates the exercise names to match the values
in this field.

Ref: https://github.com/exercism/exercism/issues/6579

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by kytrinyx** [comment]
This is failing CI, but it looks like main is also failing. Should we admin-merge?

**Comment by NobbZ** [comment]
It is not even GHA that fail but an external CI service. I was not even aware that CircleCI is enabled for any of the repositories. I always though all repos moved from Travis to GHA back then.

**Comment by NobbZ** [comment]
Seems as if a `circle.yml` exists at the repo root and hasn't been touched in the last 6 years.

I think this is the CircleCI v1 location and is not supported anymore for many years.

Personally I'd just disable the CircleCI integration for this repository.

**Comment by kytrinyx** [comment]
I've disabled Circle CI and opened a PR to delete the config #286 
Once that's been merged I'll rebase and this PR should end up in a good state.

**Pull request merged**
